services:
  - type: web
    name: faqih-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    domains:
      - al-faqih-ai.onrender.com 